[package]
name = "rspec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
rustfft = "6.0.1"
symphonia = "0.5.0"
cpal = "0.13.5"